neo4j-contrib/neo4j-graph-algorithms

algo/src/main/java/org/neo4j/graphalgo/DijkstraProc.java
algo/src/main/java/org/neo4j/graphalgo/PageRankProc.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc.java
algo/src/main/java/org/neo4j/graphalgo/impl/MSTPrim.java
core/src/main/java/org/neo4j/graphalgo/api/GraphSetup.java
core/src/main/java/org/neo4j/graphalgo/api/NodeProperties.java
core/src/main/java/org/neo4j/graphalgo/api/NodeWeights.java
core/src/main/java/org/neo4j/graphalgo/api/RelationshipWeights.java
core/src/main/java/org/neo4j/graphalgo/api/WeightMapping.java
core/src/main/java/org/neo4j/graphalgo/core/GraphLoader.java
core/src/main/java/org/neo4j/graphalgo/core/NullWeightMap.java
core/src/main/java/org/neo4j/graphalgo/core/WeightMap.java
core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraph.java
core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java
core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraph.java
core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java
core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphViewFactory.java
core/src/main/java/org/neo4j/graphalgo/core/sources/BufferedWeightMap.java
tests/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFileLoader.java
tests/src/test/java/org/neo4j/graphalgo/SimpleGraphSetup.java
tests/src/test/java/org/neo4j/graphalgo/core/GraphNegativeTest.java
tests/src/test/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactoryTest.java
tests/src/test/java/org/neo4j/graphalgo/impl/ShortestPathDijkstraTest.java

This adds the possibility to load weights for nodes, as well as some additional numeric value from an arbitrary property. This is in preparation for Label Propagation, which comes in an additional PR.
Each of the following commits can be reviewed individually to decrease the size of each change.

Node weights and property

---

algo/src/main/java/org/neo4j/graphalgo/StronglyConnectedComponentsProc.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc2.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc3.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc4.java
algo/src/main/java/org/neo4j/graphalgo/results/SCCStreamResult.java
doc/connected-components.adoc
doc/label-propagation.adoc
doc/louvain.adoc
doc/strongly-connected-components.adoc
tests/src/test/java/org/neo4j/graphalgo/algo/IterativeTarjanSCCTest.java
tests/src/test/java/org/neo4j/graphalgo/algo/SCCTunedTarjanTest.java

I change the algo.scc and algo.unionFind input parameter `clusterProperty` to `partitionProperty` and changed their default value to `partition`. 
Fixes [#186](https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/186)
I also put each sentence in it's own line for algo.scc and algo.unionFind docs and tried to replace clustering/community detection with graph partitioning wherever I found sense.

Rename clustering to graph partitioning

---

core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java

Fixes test error from travis build [#672](https://travis-ci.org/neo4j-contrib/neo4j-graph-algorithms/builds/253365523).
When there are outgoing AND incoming relationships for two nodes (`(n3)-[:TYPE {weight:0.5}]->(n6), (n6)-[:TYPE {weight:0.4}]->(n3)`), the LightGraph would assign the weight in the wrong order.

Use correct order when combining IDs for weights in LightGraph

---

algo/src/main/java/org/neo4j/graphalgo/AllShortestPathsProc.java
algo/src/main/java/org/neo4j/graphalgo/BetweennessCentralityProc.java
algo/src/main/java/org/neo4j/graphalgo/ClosenessCentralityProc.java
algo/src/main/java/org/neo4j/graphalgo/LabelPropagationProc.java
algo/src/main/java/org/neo4j/graphalgo/MSColoringProc.java
algo/src/main/java/org/neo4j/graphalgo/PageRankProc.java
algo/src/main/java/org/neo4j/graphalgo/ShortestPathDeltaSteppingProc.java
algo/src/main/java/org/neo4j/graphalgo/StronglyConnectedComponentsProc.java
algo/src/main/java/org/neo4j/graphalgo/TriangleProc.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc2.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc3.java
algo/src/main/java/org/neo4j/graphalgo/UnionFindProc4.java
doc/betweenness-centrality.adoc
doc/closeness-centrality.adoc
doc/connected-components.adoc
doc/label-propagation.adoc
doc/pagerank.adoc
doc/strongly-connected-components.adoc
doc/triangleCount.adoc

I have found few things, that might be changed, so that as default we use as many threads as possible...
algo.scc.multistep uses:
```
configuration.getNumber("concurrency", 1).intValue()
```
algo.scc.forwardBackward uses:
```
configuration.getConcurrency(1))
```
And correct me if I am wrong `algo.betweenness.exp1` seems to have hard-coded 4 threads:
```
ParallelUtil.iterateParallel(executorService, nodeCount, 4, i -> {
d.set(i, -1);
sigma.set(i, 0);
offsets.set(i, 0);
});
```
when i compare it to:
```
ParallelUtil.iterateParallel(executorService, nodeCount, Pools.DEFAULT_CONCURRENCY, i -> {
centrality.set(i, centrality.get(i) / 2.0);
});
```
I can easily change `algo.scc.*` to default to that it will use maximum threads possible
```
configuration.getConcurrency()
```

Docs Concurrency update

---

algo/src/main/java/org/neo4j/graphalgo/LabelPropagationProc.java
tests/src/test/java/org/neo4j/graphalgo/algo/LabelPropagationProcIntegrationTest.java

I can't recall why it restricted it in the first place and I don't see a technical reason why it shouldn't be supported.
Fixes #289.

Allow 'BOTH' for LPA

---

algo/src/main/java/org/neo4j/graphalgo/IsFiniteFunc.java
tests/src/test/java/org/neo4j/graphalgo/algo/IsFiniteFuncTest.java

This can help with issues such as #256 since Cypher itself does not have `Infinity` as a constant. Also adds `algo.Infinity()` and `algo.NaN()` as constants.

Add `algo.isFinite` and `algo.isInfinite`

---

core/src/main/java/org/neo4j/graphalgo/api/Graph.java
core/src/main/java/org/neo4j/graphalgo/api/HugeGraph.java
core/src/main/java/org/neo4j/graphalgo/api/HugeRelationshipWeights.java
core/src/main/java/org/neo4j/graphalgo/api/HugeWeightMapping.java
core/src/main/java/org/neo4j/graphalgo/core/HugeNullWeightMap.java
core/src/main/java/org/neo4j/graphalgo/core/HugeWeightMap.java
core/src/main/java/org/neo4j/graphalgo/core/WeightMap.java
core/src/main/java/org/neo4j/graphalgo/core/heavyweight/AdjacencyMatrix.java
core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraph.java
core/src/main/java/org/neo4j/graphalgo/core/heavyweight/RelationshipImporter.java
core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphFactory.java
core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphImpl.java
core/src/main/java/org/neo4j/graphalgo/core/lightweight/GraphImporter.java
core/src/main/java/org/neo4j/graphalgo/core/lightweight/LightGraph.java
core/src/main/java/org/neo4j/graphalgo/core/lightweight/RelationshipImporter.java
core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java
core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphViewFactory.java
core/src/main/java/org/neo4j/graphalgo/core/utils/RawValues.java
tests/src/test/java/org/neo4j/graphalgo/core/CypherExporter.java
tests/src/test/java/org/neo4j/graphalgo/core/WeightMapImportTest.java
tests/src/test/java/org/neo4j/graphalgo/core/neo4jview/GraphViewTest.java

This is somewhat of a follow-up to #444 and required for correct weighted Louvain.
The change is related to nodes that are connected to each other like so
```
CREATE (a), (b)
CREATE (a)-[{ weight: 1 }]->(b), (b)-[{weight: 2}]->(a)
```
When using BOTH to treat the graph as undirected (and only then), those two relationships are effectively one in terms of their weight, in which case we use a sorted (a,b | a <= b) as weight key. In practice, the last weight write wins. We can introduce a new configuration in a future issue that would allow the user to decide how to combine weights, e.g. a `WeightAccumulator` enum with `SUM`, `MIN`, `MAX`, `FWW`, `LWW` values.
Unfortunately, the GraphView is not able to merge those weights on-the-fly, at least not in a way that wouldn't be tailored to the …

Test and support "undirected" weights when loading as BOTH

---

core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyCypherGraphFactory.java
tests/src/test/java/org/neo4j/graphalgo/impl/LabelPropagation420CypherLoadingTest.java
tests/src/test/java/org/neo4j/graphalgo/impl/LabelPropagation420Test.java

This is pretty much how the other loaders work except the throwing of the `property doesn't exist` exception is thrown further down the stack and they only see a `null` value from the API they call.

Default weight/property loading from Cypher projections as per #464

---

benchmark/src/main/java/org/neo4j/graphalgo/bench/ClosenessCentralityBenchmark.java
benchmark/src/main/java/org/neo4j/graphalgo/utils/LongArrayBenchmark.java
benchmark/src/main/java/org/neo4j/graphalgo/utils/LongArrays.java
benchmark/src/main/java/org/neo4j/prof/Heap.java
benchmark/src/main/java/org/neo4j/unsafe/impl/batchimport/cache/ChunkedHeapFactory.java
benchmark/src/main/resources/META-INF/services/org.openjdk.jmh.profile.Profiler
core/src/main/java/org/neo4j/graphalgo/core/utils/paged/SparseLongArray.java
tests/pom.xml
tests/src/test/java/org/neo4j/graphalgo/core/utils/paged/SparseLongArrayTest.java

A bug in the SparseLongArray (#392) would falsely report a node to be existing when it was actually skipped during loading. The bug would only manifest, if a user would load the graph using `huge` and a label limitation and where some of the nodes containing the label would be connected to nodes that don't have that particular label. Heavy and cypher loading was not affected.
I changed to implementation and added some tests and benchmarks for the SparseLongArray. All in all, the new implementation is much faster in reads, which prompts me to apply similar changes to the regular `LongArray`, which we're using in quite some places.
I also compared the different possible LongArray implementations against the primitive long[] baseline as well as against some arrays from the batch importer.

Fix SparseLargeArray / HugeIdMapping contains

---

algo/src/main/java/org/neo4j/graphalgo/impl/AllShortestPaths.java
algo/src/main/java/org/neo4j/graphalgo/impl/ShortestPathAStar.java
algo/src/main/java/org/neo4j/graphalgo/impl/ShortestPathDijkstra.java
algo/src/main/java/org/neo4j/graphalgo/impl/ShortestPaths.java
core/src/main/java/org/neo4j/graphalgo/core/utils/queue/IntPriorityQueue.java
core/src/main/java/org/neo4j/graphalgo/core/utils/queue/SharedIntPriorityQueue.java
core/src/main/java/org/neo4j/graphalgo/core/utils/traverse/SimpleBitSet.java
tests/src/test/java/org/neo4j/graphalgo/algo/ShortestPathIntegrationTest.java
tests/src/test/java/org/neo4j/graphalgo/core/utils/queue/IntMinPriorityQueueTest.java
tests/src/test/java/org/neo4j/graphalgo/impl/ShortestPathDijkstraTest.java

Reported and based on the examples in #599, also fixes #599.
The basic issue is that the priority queue doesn't support duplicate values, but we might enqueue a node multiple times with different weights, coming from different paths.
The PQ is an array based heap and new nodes are enqueued by adding them to the end and then bubbling them up to their correct place.
First, we discover the target node (3) with a weight of 5 – it is places in the heap.
Then we discover the node (2) with a weight of 5. It's placed at the end of heap and doesn't bubble up, since its weight is not less than that of the previous node.
Then we discover a new path to (2) with a weight of 2. (2) is now placed at the end of the heap again and should bubble up, but the first check happens against the previously …

Fixing SSSP/D for cases where a node is queued multiple times before being traversed.

---

doc/asciidoc/all-pairs-shortest-path.adoc
doc/asciidoc/closeness-centrality.adoc
doc/asciidoc/connected-components.adoc
doc/asciidoc/harmonic-centrality.adoc
doc/asciidoc/louvain.adoc
doc/asciidoc/pagerank.adoc
doc/asciidoc/scripts/closeness-centrality.cypher
doc/asciidoc/scripts/connected-components.cypher
doc/asciidoc/scripts/harmonic-centrality.cypher
doc/asciidoc/scripts/louvain.cypher
doc/asciidoc/scripts/pagerank.cypher
doc/asciidoc/scripts/single-shortest-path.cypher
doc/asciidoc/scripts/strongly-connected-components.cypher
doc/asciidoc/strongly-connected-components.adoc
readme.adoc

Use cases and constraints were duplicated in all pairs shortest path.

Add huge projection docs

---

doc/asciidoc/all-pairs-shortest-path.adoc
doc/asciidoc/astar.adoc
doc/asciidoc/betweenness-centrality-ra-brandes.adoc
doc/asciidoc/betweenness-centrality.adoc
doc/asciidoc/closeness-centrality.adoc
doc/asciidoc/connected-components.adoc
doc/asciidoc/degree-centrality.adoc
doc/asciidoc/harmonic-centrality.adoc
doc/asciidoc/label-propagation.adoc
doc/asciidoc/louvain.adoc
doc/asciidoc/minimum-weight-spanning-tree.adoc
doc/asciidoc/pagerank.adoc
doc/asciidoc/single-shortest-path.adoc
doc/asciidoc/strongly-connected-components.adoc
doc/asciidoc/triangleCount.adoc

This PR standardizes the headers that re-appear in the documentation. 
Neo4j docs uses sentence-case for headers, so I have replaced the common headers with this format. I have also made the headers specific to the relevant algorithm wherever possible - this will assist with direct linking to use-cases, contraints, and samples.
Remaining headers, and adding anchor IDs to these headers will be handled in future PRs.

Standardize header format in the docs (on consistent headers)

---

doc/asciidoc/all-pairs-shortest-path.adoc
doc/asciidoc/astar.adoc
doc/asciidoc/betweenness-centrality-ra-brandes.adoc
doc/asciidoc/betweenness-centrality.adoc
doc/asciidoc/closeness-centrality.adoc
doc/asciidoc/connected-components.adoc
doc/asciidoc/degree-centrality.adoc
doc/asciidoc/developer-api.adoc
doc/asciidoc/harmonic-centrality.adoc
doc/asciidoc/implementers.adoc
doc/asciidoc/index.adoc
doc/asciidoc/label-propagation.adoc
doc/asciidoc/louvain.adoc
doc/asciidoc/minimum-weight-spanning-tree.adoc
doc/asciidoc/pagerank.adoc
doc/asciidoc/single-shortest-path.adoc
doc/asciidoc/strongly-connected-components.adoc
doc/asciidoc/triangleCount.adoc

This PR standardizes the titles that appear in the documentation.
Neo4j docs uses sentence-case for titles, so I have replaced the current titles with this format. I've also removed an inconsistent prefix (`Community detection:`) which was appearing on some of the algorithm titles.
Adding anchor IDs to these titles (and sub-headers) will be handled in a future PR.

Standardize title format in the docs

---

algo/src/main/java/org/neo4j/graphalgo/impl/betweenness/RABrandesBetweennessCentrality.java

This fixes the wrong operator for the maxDepth parameter of https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/524. Now the `maxDepth:1` will visit all nodes 1 hop away

Change maxDepth operator in sampled betweeneess

---

doc/asciidoc/index.adoc

Replaces #613 
Following discussion with @mneedham, this content is not required for general User Documentation purposes, and in some places is unfinished. 
As opposed to 613, this PR uses tagging to suppress the Implementers section from the documentation build only, and can be reinstated in the future if required.

Remove the Implementers section from the docs build

---

doc/asciidoc/algorithms.adoc
doc/asciidoc/index.adoc

This PR adds content to the Documentation landing page.
To enable the links in the TOC, this PR adds IDs to the following sections: 
* Introduction
* Yelp Example
* Procedures
* Algorithms
It does not include Implementers Section, which is to be suppressed in #638 
Note that Copyright information will be added to this page by @jjaderberg in a later PR

Add a TOC to docs homepage

---

doc/asciidoc/astar.adoc
doc/asciidoc/betweenness-centrality.adoc
doc/asciidoc/closeness-centrality.adoc
doc/asciidoc/harmonic-centrality.adoc
doc/asciidoc/label-propagation.adoc
doc/asciidoc/louvain.adoc
doc/asciidoc/minimum-weight-spanning-tree.adoc
doc/asciidoc/pagerank.adoc
doc/asciidoc/shortest-path.adoc
doc/asciidoc/single-shortest-path.adoc
doc/asciidoc/triangleCount.adoc
doc/asciidoc/yens-k-shortest-paths.adoc

Each algo has a header called "Versions", which doesn't make much sense. This PR changes these to "Graph type support", and adds the following text:
```The XXXX algorithm supports the following graph types:```

Change the "Versions" header to "Graph type support"

---

algo/src/main/java/org/neo4j/graphalgo/impl/ShortestPathDeltaStepping.java
tests/src/test/java/org/neo4j/graphalgo/impl/ShortestPathDeltaSteppingTest.java

Before this PR if you have an unreachable node the distance returned will be `Integer.MAX_VALUE / 100_000d` which is a bit confusing

3.4 delta stepping infinity

---

algo/src/main/java/org/neo4j/graphalgo/KShortestPathsProc.java
algo/src/main/java/org/neo4j/graphalgo/impl/yens/WeightedPathExporter.java
tests/src/test/java/org/neo4j/graphalgo/algo/YensKShortestPathsRelationshipCostsTest.java
tests/src/test/java/org/neo4j/graphalgo/algo/YensKShortestPathsTest.java

It makes it much easier to consume the output of Yens k-shortest path if we also store the distance on the generated relationships

store weights along with relationships for Yens k-shortest path

---

core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphImpl.java

Fixes some bugs for triangle counting

Make it more obvious that HugeGraph is reusing cursor state

---

algo/src/main/java/org/neo4j/graphalgo/Version.java
pom.xml
tests/src/test/java/org/neo4j/graphalgo/algo/VersionTest.java

This PR adds a really simple `RETURN algo.version()` function that returns the same version as is defined in the POM.  
The implementation is mostly borrowed from APOC, which does the same thing.
The reason why this feature is useful is that calling it:
- Verifies that algos are installed in a neo4j instance
- Doesn't require any computation overhead
- Provides useful compatibility information for later uses (i.e. only version >= X has the FooAlgorithm)
For cloud packaging, I use this technique with APOC, and it'd be nice to have in algos too since it's so trivial to implement.
Notes for consideration:
- The POM changes are what annotates the JAR with the data that permits fetching package implementation.
- The unit test is kinda/sorta bogus.  It verifies that the function is in place, …

Add algo.version() function

---

doc/asciidoc/index.adoc
doc/docbook/content-map.xml

The new categories (Similarity and Preprocessing) were inconsistent in the order of presentation, and needed to be added to the content map.

Ensure that documentation includes new categories

---

algo/src/main/java/org/neo4j/graphalgo/PageRankProc.java
algo/src/main/java/org/neo4j/graphalgo/impl/WeightedDegreeCentrality.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/BaseComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/DegreeCache.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/DegreeComputer.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugePageRank.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeWeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/NoOpDegreeComputer.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/NonWeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/NonWeightedPageRankVariant.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/PageRank.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/PageRankAlgorithm.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/PageRankVariant.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedDegreeComputer.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedPageRankVariant.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedWithCachedWeightsComputeStep.java
benchmark/src/main/java/org/neo4j/graphalgo/bench/PageRankBenchmarkLdbc.java
benchmark/src/main/java/org/neo4j/graphalgo/bench/WeightedPageRankBenchmarkLdbc.java
tests/src/test/java/org/neo4j/graphalgo/algo/PageRankProcIntegrationTest.java
tests/src/test/java/org/neo4j/graphalgo/impl/DegreeCentralityTest.java
tests/src/test/java/org/neo4j/graphalgo/impl/WeightedDegreeCentralityTest.java

A short term solution for weighted PageRank. Our attempted refactoring of Weight Maps ended up touching half the code base so we backed out for now
```
Benchmark                          (cacheWeights)  (graph)  (graphId)  (iterations)  (parallel)  Mode  Cnt      Score     Error  Units
PageRankBenchmarkLdbc.run                            HEAVY        L01             5       false  avgt   15   433.840  ± 5.404    ms/op
WeightedPageRankBenchmarkLdbc.run            true    HEAVY        L01             5       false  avgt   15   1072.329 ±  43.609  ms/op
WeightedPageRankBenchmarkLdbc.run           false    HEAVY        L01             5       false  avgt   15   4146.928 ± 113.908  ms/op
```

3.4 cache weights pagerank

---

readme.adoc

Add Balanced Triads to the list of algos on the Readme

---

algo/src/main/java/org/neo4j/graphalgo/LabelPropagationProc.java
algo/src/main/java/org/neo4j/graphalgo/StronglyConnectedComponentsProc.java
algo/src/main/java/org/neo4j/graphalgo/impl/UnionFindProcExec.java
algo/src/main/java/org/neo4j/graphalgo/results/LabelPropagationStats.java
algo/src/main/java/org/neo4j/graphalgo/results/SCCResult.java
core/src/main/java/org/neo4j/graphalgo/core/ProcedureConfiguration.java
doc/asciidoc/connected-components.adoc
doc/asciidoc/label-propagation.adoc
doc/asciidoc/strongly-connected-components.adoc
tests/src/test/java/org/neo4j/graphalgo/algo/LabelPropagationProcIntegrationTest.java
tests/src/test/java/org/neo4j/graphalgo/algo/StronglyConnectedComponentsProcIntegrationTest.java
tests/src/test/java/org/neo4j/graphalgo/algo/UnionFindProcIntegrationTest.java
tests/src/test/java/org/neo4j/graphalgo/core/ProcedureConfigurationTest.java

This PR refactors the community detection algorithms, specifically:
* All use `writeProperty` to store results. It will fall back to `partitionProperty` (the old key) if it's not specified
* Label Propagation write version overloads on the 3rd parameter so that it has the same signature as other algos. Will still respect the old signature if 4 arguments are provided

3.4 writeproperty

---

algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/ArticleRankComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/BaseComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/ComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/EigenvectorCentralityComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeArticleRankComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeBaseComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeEigenvectorCentralityComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeNonWeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugePageRank.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/HugeWeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/NonWeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/PageRank.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedComputeStep.java
algo/src/main/java/org/neo4j/graphalgo/impl/pagerank/WeightedWithCachedWeightsComputeStep.java
benchmark/src/main/java/org/neo4j/graphalgo/bench/LongIteratorsBenchmark.java
benchmark/src/main/java/org/neo4j/graphalgo/bench/PageRankBenchmarkLdbc.java

Potential solution for #861 
Benchmarks show a decrease in performance of 0.5 to 1%, well within the error margin.
Benchmarks were executed as 
```
java -jar benchmark/target/benchmark.jar -rf json -rff page-rank.json -gc true -prof gc org.neo4j.graphalgo.bench.PageRankBenchmarkLdbc.*
```
Benchmark Json files:
[bechmark-files.zip](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/3033906/bechmark-files.zip)

Use floats instead of scaled ints for PR score

---

algo/pom.xml
benchmark/pom.xml

Changes from HugeLouvain result in build errors with the current shade version: https://stackoverflow.com/questions/52221326/maven-shade-plugin-failed-to-execute-goal

Upgrade maven-shade
