neo4j-contrib/neo4j-graph-algorithms

- doc/pagerank.adoc
- doc/scripts/yelp-import.cypher
added pagerank yelp example...
Will add results tommorow.
> Add pagerank yelp example

- doc/betweenness-centrality.adoc
- doc/label-propagation.adoc
- doc/scripts/label-propagation.cypher
- doc/scripts/single-shortest-path.cypher
- doc/single-shortest-path.adoc
completes https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/420
> Add LPA docs

- benchmark/src/main/java/org/neo4j/graphalgo/bench/AllShortestPathsComparisionBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/BetweennessCentralityBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/BetweennessComparisionBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/ParallelUnionFindBenchmark.java
- tests/src/test/java/org/neo4j/graphalgo/core/utils/ParallelUtilTest.java
The latest build did not complete b/c the ms coloring benchmark takes forever or might even never finish.
> Reduce Benchmark overhead so that travis has a chance to finish

- algo/src/main/java/org/neo4j/graphalgo/LabelPropagationProc.java
- tests/src/test/java/org/neo4j/graphalgo/algo/LabelPropagationProcIntegrationTest.java
> Allow 'BOTH' for LPA

- algo/src/main/java/org/neo4j/graphalgo/IsFiniteFunc.java
- tests/src/test/java/org/neo4j/graphalgo/algo/IsFiniteFuncTest.java
> Add `algo.isFinite` and `algo.isInfinite`

- benchmark/src/main/java/org/neo4j/prof/JFR.java
- core/src/main/java/org/neo4j/graphalgo/api/HugeRelationshipIntersect.java
- core/src/main/java/org/neo4j/graphalgo/api/HugeRelationshipIterator.java
- core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphImpl.java
- core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphIntersectImpl.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/paged/ByteArray.java
- tests/src/test/java/org/neo4j/graphalgo/core/huge/HugeIntersectionTest.java
> Add intersect interface to HugeGraph

- doc/scripts/single-shortest-path.cypher
- doc/single-shortest-path.adoc
fix https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/530
> Filtering infinity docs

- algo/src/main/java/org/neo4j/graphalgo/ShortestPathProc.java
- algo/src/main/java/org/neo4j/graphalgo/impl/ShortestPathAStar.java
- tests/src/test/java/org/neo4j/graphalgo/algo/ShortestPathAStarTest.java
Heuristic function is for geospatial distances.
Tested on a graph of about 9000 nodes and found to be faster than Dijkstra implementation by at least 2 orders of magnitude.
@mneedham built against 3.2 upstream branch. Thanks for the review.
> Added A* Implementation for Shortest Path

- algo/pom.xml
- algo/src/main/java/org/neo4j/graphalgo/impl/msbfs/HugeBiMultiBitSet32.java
- core/pom.xml
- core/src/main/java/org/neo4j/graphalgo/core/utils/paged/HugeLongArray.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/paged/PagedDisjointSetStruct.java
- tests/src/test/java/org/neo4j/graphalgo/core/utils/paged/HugeLongArrayTest.java
> More HugeLongArray improvements

- algo/src/main/java/org/neo4j/graphalgo/ShortestPathProc.java
- doc/asciidoc/algorithms.adoc
- doc/asciidoc/astar.adoc
- doc/asciidoc/index.adoc
- doc/asciidoc/scripts/astar.cypher
I took the intro and explanation from O'Reilly Graph Database
> Astar docs

- doc/asciidoc/index.adoc
- doc/asciidoc/yelp-intro.adoc
An edit on the Yelp example in the Graph Algorithm documentation, mostly amending style issues.
> Edit on the Yelp example

- readme.adoc
An edit on the Introduction of the Graph Algorithm documentation, mostly amending style issues.
I moved the Feedback statements to the end of the README, as it seemed to make more sense there. I also tagged it, so the Feedback request wouldn't appear in the documentation build.
> Edit on the Introduction section/README

- algo/pom.xml
- doc/asciidoc/index.adoc
Simplifies the header on the list of graph algo procedures in the documentation.
> Rename the procedures section in the documentation

- doc/asciidoc/algorithms.adoc
An edit on the opening paragraphs of the algorithm documentation, mostly amending style issues.
Edits for the documentation on each of the algorithms, and implementation will be handled in other PRs.
> Edit on the Algorithm opening paragraphs

- doc/asciidoc/pagerank.adoc
#602 was closed as some changes were incorporated into other PRs.
This PR brings forward just the editorial changes for the PageRank documentation (not including the Implementers section, which will be handled separately)
> Edit on the PageRank documentation 

- doc/asciidoc/louvain.adoc
- doc/asciidoc/pagerank.adoc
Additionally fixes an inconsistency on the PageRank doc
> Edit on the Louvain algorithm docs

- doc/asciidoc/algorithms.adoc
- doc/asciidoc/all-pairs-shortest-path.adoc
- doc/asciidoc/astar.adoc
- doc/asciidoc/betweenness-centrality.adoc
- doc/asciidoc/closeness-centrality.adoc
- doc/asciidoc/connected-components.adoc
- doc/asciidoc/harmonic-centrality.adoc
- doc/asciidoc/index.adoc
- doc/asciidoc/label-propagation.adoc
- doc/asciidoc/louvain.adoc
- doc/asciidoc/minimum-weight-spanning-tree.adoc
- doc/asciidoc/pagerank.adoc
- doc/asciidoc/shortest-path.adoc
- doc/asciidoc/single-shortest-path.adoc
- doc/asciidoc/strongly-connected-components.adoc
- doc/asciidoc/triangleCount.adoc
- doc/asciidoc/yelp-intro.adoc
- doc/asciidoc/yens-k-shortest-paths.adoc
- doc/build.gradle
- doc/css/chunked-base.css
- readme.adoc
Complete work necessary to publish documentation.
> Prepare to publish docs

- doc/asciidoc/yens-k-shortest-paths.adoc
https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/3.2/algo/src/main/java/org/neo4j/graphalgo/KShortestPathsProc.java#L80
> Fix default direction yens-k docs

- algo/src/main/java/org/neo4j/graphalgo/impl/walking/AbstractWalkOutput.java
- algo/src/main/java/org/neo4j/graphalgo/impl/walking/NodeWalker.java
- algo/src/main/java/org/neo4j/graphalgo/impl/walking/WalkPath.java
- algo/src/main/java/org/neo4j/graphalgo/impl/walking/WalkResult.java
- algo/src/main/java/org/neo4j/graphalgo/results/VirtualNode.java
- algo/src/main/java/org/neo4j/graphalgo/results/VirtualRelationship.java
- algo/src/main/java/org/neo4j/graphalgo/walking/NodeWalkerProc.java
- core/src/main/java/org/neo4j/graphalgo/api/HugeGraph.java
- core/src/main/java/org/neo4j/graphalgo/api/HugeRelationshipAccess.java
- core/src/main/java/org/neo4j/graphalgo/api/RelationshipAccess.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/AdjacencyMatrix.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraph.java
- core/src/main/java/org/neo4j/graphalgo/core/huge/HugeGraphImpl.java
- core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/QueueBasedSpliterator.java
- doc/asciidoc/random-walk.adoc
- doc/asciidoc/scripts/random-walk.cypher
- tests/pom.xml
- tests/src/test/java/org/neo4j/graphalgo/walking/Node2VecWalkTest.java
- tests/src/test/java/org/neo4j/graphalgo/walking/RandomWalkLargeResultTest.java
* based on work from the students group at the HPI, see meta-exp.github.io
* supports random and node2vec strategy
* extended Graph API with getRelationship(node, index)
* `algo.randomWalk.stream(label, rel-type, start, steps, walks, {config}) yield nodes, path`
* Added basic documentation (not linked yet)
> Added Ability to perform Random Walks

- algo/src/main/java/org/neo4j/graphalgo/JaccardProc.java
- algo/src/test/java/org/neo4j/graphalgo/IntersectionTest.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/IntersectionBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/PageRankBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/PageRankBenchmarkLdbc.java
- tests/src/test/java/org/neo4j/graphalgo/algo/JaccardTest.java
Using sorted arrays and comparing values at incrementing indexes
TODO SIMD
> Jaccard intersect Optimization

- algo/src/main/java/org/neo4j/graphalgo/BalancedTriadsProc.java
- tests/src/test/java/org/neo4j/graphalgo/algo/BalancedTriadsIntegrationTest.java
Fixes  https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/705
> Fix balancedTriads streaming algorithm

- algo/src/main/java/org/neo4j/graphalgo/similarity/SimilarityProc.java
- tests/src/test/java/org/neo4j/graphalgo/algo/similarity/CosineTest.java
- tests/src/test/java/org/neo4j/graphalgo/algo/similarity/EuclideanTest.java
- tests/src/test/java/org/neo4j/graphalgo/algo/similarity/JaccardTest.java
@jexp not sure if there's an easier way than this?
> handle arrays of values - this is what we get if we store properties

- algo/src/main/java/org/neo4j/graphalgo/LouvainProc.java
- algo/src/main/java/org/neo4j/graphalgo/impl/louvain/Louvain.java
- algo/src/main/java/org/neo4j/graphalgo/impl/louvain/LouvainCommunityExporter.java
- doc/asciidoc/louvain.adoc
- tests/src/test/java/org/neo4j/graphalgo/algo/LouvainClusteringIntegrationTest.java
- tests/src/test/java/org/neo4j/graphalgo/impl/LouvainMultiLevelTest.java
Fixing backwards compatibility things as described in https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/736
> 3.4 louvain backward

- doc/asciidoc/index.adoc
- doc/build.gradle
Please merge forward to the latest version of the docs
> Add new 2019 copyright + license details to GA docs

- doc/asciidoc/docinfo.xml
> Add the docinfo.xml file that is used to display copyright

- doc/asciidoc/all-pairs-shortest-path.adoc
- doc/asciidoc/articlerank.adoc
- doc/asciidoc/astar.adoc
- doc/asciidoc/balanced-triads.adoc
- doc/asciidoc/betweenness-centrality-ra-brandes.adoc
- doc/asciidoc/betweenness-centrality.adoc
- doc/asciidoc/closeness-centrality.adoc
- doc/asciidoc/connected-components.adoc
- doc/asciidoc/harmonic-centrality.adoc
- doc/asciidoc/label-propagation.adoc
- doc/asciidoc/linkprediction-adamic-adar.adoc
- doc/asciidoc/linkprediction-common-neighbors.adoc
- doc/asciidoc/linkprediction-preferential-attachment.adoc
- doc/asciidoc/linkprediction-resource-allocation.adoc
- doc/asciidoc/linkprediction-same-community.adoc
- doc/asciidoc/linkprediction-total-neighbors.adoc
- doc/asciidoc/louvain.adoc
- doc/asciidoc/minimum-weight-spanning-tree.adoc
- doc/asciidoc/pagerank.adoc
- doc/asciidoc/random-walk.adoc
- doc/asciidoc/shortest-path.adoc
- doc/asciidoc/similarity-cosine.adoc
- doc/asciidoc/similarity-euclidean.adoc
- doc/asciidoc/similarity-jaccard.adoc
- doc/asciidoc/similarity-overlap.adoc
- doc/asciidoc/similarity-pearson.adoc
- doc/asciidoc/single-shortest-path.adoc
- doc/asciidoc/strongly-connected-components.adoc
- doc/asciidoc/triangleCount.adoc
- doc/asciidoc/yens-k-shortest-paths.adoc
Each algorithm has several sub headers, and in some cases quite a lot of content. To make it easier for readers to navigate to specific sections, this PR adds a table of contents to the top of each algorithm.
> Add tables of contents to each of the Algorithms

- core/src/main/java/org/neo4j/graphalgo/api/GraphSetup.java
- core/src/main/java/org/neo4j/graphalgo/core/DuplicateRelationshipsStrategy.java
- core/src/main/java/org/neo4j/graphalgo/core/GraphLoader.java
- core/src/main/java/org/neo4j/graphalgo/core/ProcedureConfiguration.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/CypherLoadingUtils.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/CypherNodeLoader.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/CypherRelationshipLoader.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyCypherGraphFactory.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/MergedRelationships.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/NodeLoader.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/NodeRowVisitor.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/Nodes.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/RelationshipRowVisitor.java
- core/src/main/java/org/neo4j/graphalgo/core/heavyweight/Relationships.java
- tests/src/test/java/org/neo4j/graphalgo/core/heavyweight/HeavyCypherGraphParallelFactoryTest.java
- tests/src/test/java/org/neo4j/graphalgo/core/heavyweight/HeavyCypherGraphSequentialFactoryTest.java
- tests/src/test/java/org/neo4j/graphalgo/core/heavyweight/MergedRelationshipsTest.java
- tests/src/test/java/org/neo4j/graphalgo/core/heavyweight/RelationshipRowVisitorTest.java
This PR:
* Pulls apart the Cypher loader so that it's easier to test the individual components
* Fixes a bug when accumulating weights on non parallel loading
> Refactoring Cypher Loading Code

- doc/asciidoc/pagerank.adoc
Judging by the code we can update the docs:
https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/a17e8eb176b87290ab0f838a0a1411969feef8a1/algo/src/main/java/org/neo4j/graphalgo/PageRankProc.java#L150
> Update pagerank undirected docs

- algo/src/main/java/org/neo4j/graphalgo/impl/BaseLabelPropagation.java
- algo/src/main/java/org/neo4j/graphalgo/impl/HugeLabelPropagation.java
- algo/src/main/java/org/neo4j/graphalgo/impl/LabelPropagation.java
- algo/src/main/java/org/neo4j/graphalgo/impl/LabelPropagationAlgorithm.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/LongIteratorsBenchmark.java
- benchmark/src/main/java/org/neo4j/graphalgo/bench/RandomlySwitchingLongIterator.java
- core/src/main/java/org/neo4j/graphalgo/core/huge/loader/HugeIdMap.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/BiLongFunction.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/LazyBatchCollection.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/RandomIntIterable.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/RandomIntIterator.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/RandomLongIterable.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/RandomLongIterator.java
- tests/src/test/java/org/neo4j/graphalgo/core/utils/RandomIntIteratorTest.java
- tests/src/test/java/org/neo4j/graphalgo/core/utils/RandomLongIteratorTest.java
- tests/src/test/java/org/neo4j/graphalgo/impl/LabelPropagation420Test.java
This one includes #857, so that one should be merged first.
> Improve randomness for LPA

- algo/src/main/java/org/neo4j/graphalgo/impl/HugeParallelUnionFindFJMerge.java
- algo/src/main/java/org/neo4j/graphalgo/impl/HugeParallelUnionFindQueue.java
- algo/src/main/java/org/neo4j/graphalgo/impl/ParallelUnionFindFJMerge.java
- algo/src/main/java/org/neo4j/graphalgo/impl/ParallelUnionFindQueue.java
- algo/src/test/java/org/neo4j/graphalgo/impl/ParallelUnionFindQueueTest.java
- algo/src/test/java/org/neo4j/graphalgo/impl/UnionFindSafetyTest.java
- core/src/main/java/org/neo4j/graphalgo/core/utils/ExceptionUtil.java
> Prevent UF deadlock

- benchmark/src/main/java/org/neo4j/graphalgo/bench/ClusteringBenchmark.java
Co-authored-by: Philip Stutz <philip.stutz@gmail.com>
> Fix compilation error in ClusteringBenchmark
